name: multipass-sshfs
title: SSHFS for Multipass instances
summary: A network filesystem client for mounting host directories
description: |
  SSHFS allows you to mount a remote filesystem using SFTP via Multipass.
  Use `multipass mount` to mount a host directory in a Multipass instance.
license: GPL-2.0

version: git
confinement: strict
base: core22
grade: stable

apps:
  env:
    command: bin/busybox env
    environment:
      LD_LIBRARY_PATH: $SNAP/lib

parts:
  libfuse:
    plugin: meson
    source: https://github.com/libfuse/libfuse.git
    source-tag: fuse-3.17.1
    meson-parameters:
    - --prefix=/
    - --libdir=lib/
    - --buildtype=release
    - -Dutils=false
    - -Dexamples=false
    build-packages:
    - pkg-config
    - meson
    - ninja-build
    stage:
    - -bin/
    - -etc/
    - -sbin/
    - -dev/
    - -share/
    prime:
    - -include/
    - -lib/pkgconfig/

  sshfs:
    after:
    - libfuse
    plugin: meson
    source: https://github.com/libfuse/sshfs.git
    source-tag: sshfs-3.7.3
    meson-parameters:
    - --prefix=/
    - --buildtype=release
    build-packages:
    - libglib2.0-dev
    - meson
    - ninja-build
    stage:
    - -sbin/

  busybox-static:
    plugin: dump
    source: .
    stage-packages:
    - busybox-static
